apiVersion: v1 
kind: Pod 
metadata:
  name: springapppod
  labels:
    app: springapp
spec:
  containers:
  - name: springappcontainer
    image: 015901552966.dkr.ecr.ap-south-1.amazonaws.com/springboot-app:${buildnumber}
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
      requests:
        cpu: "300m"
        memory: "300Mi"
    env:
    - name: MONGO_DB_USERNAME
      value: rahman146
    - name: MONGO_DB_PASSWORD
      value: rahman@146
    - name: MONGO_DB_HOSTNAME
      value: mongodb 
    ports:
    - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: springappsvc
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080


---

apiVersion: v1 
kind: apiVersion: v1
kind: Pod
metadata:
  name: mongodbpod
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodbcontainer
    image: mongo 
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
      requests:
        cpu: "300m"
        memory: "300Mi"
    env: 
    - name: MONGO_INITDB_ROOT_USERNAME
      value: rahman146
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: rahman@146
    ports:
      - containerPort: 27017


---


apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc 
spec:
  selector:
    app: mongodb 
  ports:
  - port: 27017
    targetPort: 27017

    


